### ISSUE TITLE
Use key instead of url

### ISSUE THREAD

**Issue by pgr0ss** [thumbor-community/aws#29]
I think this line is supposed to use `key` instead of `url`:
https://github.com/thumbor-community/aws/blob/74990287aa02218897380d85e35bc293580cc53c/tc_aws/loaders/s3_loader.py#L30

It looks like the `url` still includes the bucket name, but the `key` looks correct.

**Comment by Bladrak** [comment]
@pgr0ss seems you're right, could you submit a PR with the edit? And add some test coverage on this?

**Comment by pgr0ss** [comment]
I tried to add a test, but I'm having trouble. I can't get my new test to fail, even when I explicitly raise in the check. Can you help me figure out what I'm doing wrong? I haven't written python in a while, and I've never used vows.

https://github.com/pgr0ss/aws/commit/37a0b51fb2215219175bad1a2522920ead7521dd#diff-77c2dd61924c56b9f0a85ad0ba044663R66

**Comment by Bladrak** [comment]
@pgr0ss I commented directly on your diff :)

**Comment by Bladrak** [comment]
@pgr0ss I noticed some issues in the code while looking into the tests, I've fixed those issues in the commit https://github.com/thumbor-community/aws/commit/2ae372724916cc88022426855c04551fb54eb00c 
There's also an update on the tests that were always passing due to async, they are now more consistent.

Thanks for reporting this and working on it! I've released 1.3.2 on pypi with this fix. If you could close the issue once you checked it's resolved.

**Comment by pgr0ss** [comment]
I just checked and it's working for me. Thanks!
