### ISSUE TITLE
Fix thumbor required versions (in future releases)

### ISSUE THREAD

**Issue by stefanhorning** [thumbor-community/aws#56]
As you can't guarantee that a tc_aws version will be compatible with all future Thumbor releases you should probably don't just use a greater then requirement, such as `>=5.2`. I currenly have the problem that this installs thumbor 6.0 with the tc_aws 2.0 release which somehow breaks (at least when keeping configs identical). To avoid this in the future it would be nice to pin the the dependency to specific version or at least just a range of versions that are guaranteed to work together with the tc_aws release.

Thanks for the consideration.

**Comment by Bladrak** [comment]
I see your point indeed, and often face the same issues when dealing with pip installations. However, we can guarantee that a version of tc_aws works with identified current or previous versions of a dependency, but we can't plan for BC Breaks as of now, which is why tc_aws is now following the thumbor versioning. I however can't really plan which future versions of dependency will break tc_aws, and so can't put an upper bound on our dependencies.

**Comment by stefanhorning** [comment]
All I was sugesting is an upper limit of thumbor versions to protect against possible thumbor breakages. You can of course still bump this in each tc_aws release, as you already do with the lower limit.

**Comment by Bladrak** [comment]
I see your point, but I can't really know which future version will break the changes for the upper limit.

**Comment by stefanhorning** [comment]
Usually major versions bring breaking changes while minor ones don't so if you want to keep your range as open as possible maybe restrict it to the same major version if that's feasable.

But it looks like you have your reasons not to do that, so I will leave you to it then ;)

**Comment by Bladrak** [comment]
I'll check with Thumbor maintainers on how they handle this, indeed it should be enough to filter based on that :)

**Comment by stefanhorning** [comment]
Thanks!
