### ISSUE TITLE
Disabling saving WebP format on STORAGE when AUTO_WEBP = True

### ISSUE THREAD

**Issue by achrafSallemi** [thumbor-community/aws#97]
One of the functionalities of Thumbor is saving the source image but we always save it as WebP format on S3 only for RESULT_STORAGE but not for STORAGE. 
Which lead me to an error on RemoteCv while we reading source image from S3(Webp is not supported on reading from S3).

Solution: 
I would suggest adding a new environment variable (like ALLOW_STORAGE_WEBP) which will save source image as WebP format in case the var is set to True.
OR
Disabling the WebP format saving completely on STORAGE & follow thumbor functionalities by saving WebP format only  on RESULT_STORAGE.

**Comment by Bladrak** [comment]
Hello @achrafSallemi :) Can you be more specific? What are you trying to achieve and why?

**Comment by achrafSallemi** [comment]
hello  @Bladrak I updated the content to be clearer.

**Comment by Bladrak** [comment]
Thanks, I'm wondering whether it's not an issue with your config.
Can you copy/paste it?

**Comment by achrafSallemi** [comment]
https://github.com/APSL/remotecv_aws/issues/1

**Comment by aoqfonseca** [comment]
I believe that is not a problem of thumbor or thumbor aws.  I consider this an improve (new feature) for thumbor  itself (we just overwrite the result storage to use s3 ), because, in your case, you read directly from s3. 

Other, thumbor has a config that disables the webp feature that you can use to avoid this kind of problem.

**Comment by Bladrak** [comment]
As mentionned by @aoqfonseca this seems rather an improvement on Thumbor's side. Closing here.
